#cloud-config
write_files:
  - path: /etc/replicated.conf
    permissions: '0640'
    content: |
      {
          "DaemonAuthenticationType":          "password",
          "DaemonAuthenticationPassword":      "${tfe_password}",
          "TlsBootstrapType":                  "server-path",
          "TlsBootstrapHostname":              "${dns_hostname}.${dns_zonename}",
          "TlsBootstrapCert":                  "/var/tmp/server.crt",
          "TlsBootstrapKey":                   "/var/tmp/server.key",
          "BypassPreflightChecks":             true,
          "ImportSettingsFrom":                "/etc/tfe_settings.json",
          "LicenseFileLocation":               "/var/tmp/${filename_license}"
      }
  - path: /etc/tfe_settings.json
    permissions: '0640'
    content: |
      {
         "aws_instance_profile": {
              "value": "1"
          },
          "enc_password": {
              "value": "${tfe_password}"
          },
          "hairpin_addressing": {
              "value": "0"
          },
          "hostname": {
              "value": "${dns_hostname}.${dns_zonename}"
          },
          "pg_dbname": {
              "value": "${pg_dbname}"
          },
          "pg_netloc": {
              "value": "${pg_address}"
          },
          "pg_password": {
              "value": "${rds_password}"
          },
          "pg_user": {
              "value": "postgres"
          },
          "placement": {
              "value": "placement_s3"
          },
          "production_type": {
              "value": "external"
          },
          "s3_bucket": {
              "value": "${tfe_bucket}"
          },
          "s3_endpoint": {},
          "s3_region": {
              "value": "${region}"
          }
      }
  - path: /var/tmp/configure_server.sh 
    permissions: '0750'
    content: |
      #!/bin/bash
      
      # Wait until there is internet before continue
      until ping -c1 google.com &>/dev/null; do
       echo "waiting for networking to initialise"
       sleep 3 
      done 
      
      # add ssh key alvaro
      curl -sL https://raw.githubusercontent.com/kikitux/curl-bash/master/provision/add_github_user_public_keys.sh | GITHUB_USER=kikitux bash
      
      # add ssh key patrick
      curl -sL https://raw.githubusercontent.com/kikitux/curl-bash/master/provision/add_github_user_public_keys.sh | GITHUB_USER=munnep bash
      
      
      # Set swappiness
      if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
      fi
      
      if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
        echo never > /sys/kernel/mm/transparent_hugepage/defrag
      fi
      
      # heavy swap vm.swappiness=80
      # no swap vm.swappiness=1
      sysctl vm.swappiness=1
      sysctl vm.min_free_kbytes=67584
      sysctl vm.drop_caches=1
      # make it permanent over server reboots
      echo vm.swappiness=1 >> /etc/sysctl.conf
      echo vm.min_free_kbytes=67584 >> /etc/sysctl.conf
      
      # configure the disks and mount points
      SWAP=/dev/$(lsblk|grep nvme | grep -v nvme0n1 |sort -k 4 -r | awk '{print $1}'| awk '(NR==1)')
      DOCKER=/dev/$(lsblk|grep nvme | grep -v nvme0n1 |sort -k 4 -r | awk '{print $1}'| awk '(NR==2)')
      
      echo $SWAP
      echo $DOCKER
      
      # swap
      # if SWAP exists
      # we format if no format
      if [ -b $SWAP ]; then
      	blkid $SWAP
      	if [ $? -ne 0 ]; then
      		mkswap $SWAP
      	fi
      fi
      
      # if SWAP not in fstab
      # we add it
      grep "swap" /etc/fstab
      if [ $? -ne 0 ]; then
        SWAP_UUID=`blkid $SWAP| awk '{print $2}'`
      	echo "$SWAP_UUID swap swap defaults 0 0" | tee -a /etc/fstab
      	swapon -a
      fi
      
      # docker
      # if DOCKER exists
      # we format if no format
      if [ -b $DOCKER ]; then
      	blkid $DOCKER
      	if [ $? -ne 0 ]; then
      		mkfs.xfs $DOCKER
      	fi
      fi
      
      # if DOCKER not in fstab
      # we add it
      grep "/var/lib/docker" /etc/fstab
      if [ $? -ne 0 ]; then
        DOCKER_UUID=`blkid $DOCKER| awk '{print $2}'`
      	echo "$DOCKER_UUID /var/lib/docker xfs defaults 0 0" | tee -a /etc/fstab
      	mkdir -p /var/lib/docker
      	mount -a
      fi
      
      # install requirements for tfe
      yum -y update
      yum -y install unzip
  - path: /var/tmp/download_and_unpack_software.sh 
    permissions: '0750'
    content: |
      #!/usr/bin/env bash
      
      # install aws cli
      pushd /var/tmp
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install --bin-dir /usr/bin --install-dir /usr/local/aws-cli --update
      
      # Download files from the bucket
      aws s3 cp s3://${tag_prefix}-software/${filename_license} /var/tmp/${filename_license}
      aws s3 cp s3://${tag_prefix}-software/certificate_pem /var/tmp/certificate_pem
      aws s3 cp s3://${tag_prefix}-software/issuer_pem /var/tmp/issuer_pem
      aws s3 cp s3://${tag_prefix}-software/private_key_pem /var/tmp/server.key
      
      # Create a full chain from the certificates
      cat /var/tmp/certificate_pem >> /var/tmp/server.crt
      cat /var/tmp/issuer_pem >> /var/tmp/server.crt
  - path: /var/tmp/install_tfe.sh   
    permissions: '0750'
    content: |
      #!/usr/bin/env bash
      # disable selinux
      setenforce 0
      getenforce
      
      # Get the public IP of the instance
      PUBLIC_IP=`curl http://169.254.169.254/latest/meta-data/public-ipv4`
      
      pushd /var/tmp
      curl -o install.sh https://install.terraform.io/ptfe/stable
      
      
      if [ "${tfe_release_sequence}" ] ; then
        bash ./install.sh release-sequence=${tfe_release_sequence} no-proxy private-address=${tfe-private-ip} public-address=$PUBLIC_IP
      else
        bash ./install.sh no-proxy private-address=${tfe-private-ip} public-address=$PUBLIC_IP
      fi
runcmd:
  - sudo bash /var/tmp/configure_server.sh 
  - sudo bash /var/tmp/download_and_unpack_software.sh 
  - sudo bash /var/tmp/install_tfe.sh 
